=== aivalisco/testRepository/XMLBeispiel01/personen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Personen (Person+)>
<!ELEMENT Person (Name, Alter, Stadt)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Alter (#PCDATA)>
<!ELEMENT Stadt (#PCDATA)>

=== aivalisco/testRepository/XMLBeispiel01/personen.xml
<!DOCTYPE Personen SYSTEM "personen.dtd">
<Personen>
    <Person>
        <Name>Anna Schmidt</Name>
        <Alter>25</Alter>
        <Stadt>München</Stadt>
    </Person>
    <Person>
        <Name>Klaus Müller</Name>
        <Alter>40</Alter>
        <Stadt>Hamburg</Stadt>
    </Person>
</Personen>
